#!/usr/bin/bash
bash input_compare_allvslongest.sh genes_annotated_filters_stats_longest_deepgoplus_depth.txt genes_annotated_filters_stats_all_deepgoplus_depth.txt deepgoplus_depth_allvslongest.txt
bash input_compare_allvslongest.sh genes_annotated_filters_stats_longest_deepgoplus_threshold_depth.txt genes_annotated_filters_stats_all_deepgoplus_threshold_depth.txt deepgoplus_threshold_depth_allvslongest.txt  
bash input_compare_allvslongest.sh genes_annotated_filters_stats_longest_eggnog_depth.txt genes_annotated_filters_stats_all_eggnog_depth.txt eggnog_depth_allvslongest.txt
bash input_compare_allvslongest.sh genes_annotated_filters_stats_longest_gopredsim_prott5.txt genes_annotated_filters_stats_all_gopredsim_prott5.txt prott5_allvslongest.txt
bash input_compare_allvslongest.sh genes_annotated_filters_stats_longest_gopredsim_prott5_threshold.txt genes_annotated_filters_stats_all_gopredsim_prott5_threshold.txt prott5_threshold_allvslongest.txt
bash input_compare_allvslongest.sh genes_annotated_filters_stats_longest_gopredsim_seqvec.txt genes_annotated_filters_stats_all_gopredsim_seqvec.txt seqvec_allvslongest.txt
bash input_compare_allvslongest.sh genes_annotated_filters_stats_longest_gopredsim_seqvec_threshold.txt genes_annotated_filters_stats_all_gopredsim_seqvec_threshold.txt seqvec_threshold_allvslongest.txt
